LHOS-AEGIS-360: main/main.cpp File Reference
main.cpp File Reference
#include <cstdio>
#include <cstring>
#include "crc16.hpp"
#include "parser.hpp"
#include "pool.hpp"
Functions
void app_main ()
Function Documentation
app_main()
void app_main ()
Definition at line 7 of file main.cpp.
References aegis::PacketPool::alloc(), aegis::crc16::ccitt(), aegis::PacketParser::feed_bytes(), aegis::PacketParser::init(), aegis::PacketPool::init(), and aegis::PacketPool::release().