LHOS-AEGIS-360: tests/test_crc16.cpp File Reference
test_crc16.cpp File Reference
#include "unity.h"
#include "crc16.hpp"
Functions
void setUp (void)
void tearDown (void)
TEST_CASE ("CRC16-CCITT known vector", "[crc16]")
TEST_CASE ("CRC16 to hex", "[crc16]")
TEST_CASE ("CRC16 empty data", "[crc16]")
Function Documentation
setUp()
void setUp (void)
Definition at line 4 of file test_crc16.cpp.
tearDown()
void tearDown (void)
Definition at line 5 of file test_crc16.cpp.
TEST_CASE() [1/3]
TEST_CASE ("CRC16 empty data" , "" [crc16])
Definition at line 19 of file test_crc16.cpp.
References crc16::ccitt_false().
TEST_CASE() [2/3]
TEST_CASE ("CRC16 to hex" , "" [crc16])
Definition at line 13 of file test_crc16.cpp.
References crc16::to_hex().
TEST_CASE() [3/3]
TEST_CASE ("CRC16-CCITT known vector" , "" [crc16])
Definition at line 7 of file test_crc16.cpp.
References crc16::ccitt_false().