[platformio]
default_envs = development_hub2

[common]
; Common settings for all environments

extra_scripts =
	pre:load_env.py
platform = espressif32@6.7.0
platform_packages = framework-arduinoespressif32
board = esp32-s3-wroom-1-N8R8
framework = arduino

; Build options
build_unflags = -std=gnu++11
build_flags =
		-D ASYNC_A7670_USE_PSRAM
		-D CORE_DEBUG_LEVEL=1
		-D ARDUINO_USB_CDC_ON_BOOT=0
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
		-std=gnu++17
		-D ARDUINOJSON_USE_LONG_LONG=1 
		-D ARDUINOJSON_SLOT_OFFSET_SIZE=2
		-D CONFIG_BT_NIMBLE_EXT_ADV
		-D MYNEWT_VAL_BLE_TRANSPORT_EVT_SIZE=251
		-Ilib/ESP32S3_CAN/src
		-Ilib/ARD1939ESP32S3/src
		-D TWAI_DEBUG
		-D TWAI_DEBUG_ESP32
		-D TWAI_DEBUG_ESP32_ISR
		-D TWAI_DEBUG_ESP32_ISR_RX
		-D TWAI_DEBUG_ESP32_ISR_TX
		-D TWAI_DEBUG_ESP32_ISR_ERROR
		-D TWAI_DEBUG_ESP32_ISR_WAKEUP
		-D USE_CANBUS
		-D DECODE_J1939 
		
		-Wno-error
		; -D LAYRZ_BLE_5_ADV
		; === NimBLE Buffer Configuration ===
    ; Increase mbuf pools (memory buffers for BLE operations)
    -DMYNEWT_VAL_MSYS_1_BLOCK_COUNT=35   
    -DMYNEWT_VAL_MSYS_1_BLOCK_SIZE=245
		-DCONFIG_BT_NIMBLE_ATT_PREFERRED_MTU=512
		-DCONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=8192
		-DCONFIG_BT_NIMBLE_MEM_ALLOC_MODE_EXTERNAL

    
    ; ; Add secondary pool for larger data
    ; -DMYNEWT_VAL_MSYS_2_BLOCK_COUNT=32  
    ; -DMYNEWT_VAL_MSYS_2_BLOCK_SIZE=1024 
    
    ; ; BLE Host buffer configuration
    ; -DMYNEWT_VAL_BLE_HS_EVT_BUF_SIZE=512 
    ; -DMYNEWT_VAL_BLE_HS_HCI_EVT_BUF_SIZE=512
    
    ; ATT (Attribute Protocol) configuration
    ; -DMYNEWT_VAL_BLE_ATT_PREFERRED_MTU=512 
    ; -DMYNEWT_VAL_BLE_ATT_SVR_MAX_PREP_ENTRIES=4
    
    ; ; L2CAP buffer configuration
    ; -DMYNEWT_VAL_BLE_L2CAP_COC_MPS=1024
    ; -DMYNEWT_VAL_BLE_L2CAP_MAX_CHANS=8 
    
    ; ; GATT server configuration
    ; -DMYNEWT_VAL_BLE_GATT_MAX_PROCS=8
    ; -DMYNEWT_VAL_BLE_GATTS_MAX_NOTIFICATIONS=16 
    ; ; Host flow control
    ; -DMYNEWT_VAL_BLE_HS_FLOW_CTRL=1  
    ; -DMYNEWT_VAL_BLE_HS_FLOW_CTRL_ITVL=1000 
    ; -DMYNEWT_VAL_BLE_HS_FLOW_CTRL_THRESH=2 
    
    ; ; Connection parameters
    ; -DMYNEWT_VAL_BLE_MAX_CONNECTIONS=4
    
    ; ; Memory allocation
    ; -DMYNEWT_VAL_OS_MEMPOOL_CHECK=0 
board_build.partitions = partitions.csv
board_build.ota_required = yes
board_build.sdkconfig = sdkconfig.defaults

; Dependencies
lib_deps =
	OBD2
	SPI
	https://github.com/PaulStoffregen/Time.git
	Adafruit NeoPixel@1.12.0
	ArduinoHttpClient@0.5.0
	ArduinoJson@6.21.4
	EspSoftwareSerial@8.2.0
	FS@2.0.0
	LittleFS@2.0.0
	Preferences@2.0.0
	WiFi@2.0.0
	WiFiClientSecure@2.0.0
	; digitaldragon/SSLClient @ ^1.3.2
	; mobizt/ESP_SSLClient@^2.2.3
	; hideakitai/CRCx@^0.4.0
	;h2zero/NimBLE-Arduino @ 2.3.7
	ModbusClient=https://github.com/eModbus/eModbus.git
	; dennis-ard/Arducam_Mega @ ^2.0.9
	https://github.com/ArduCAM/Arducam_Mega

; Watchers 
monitor_speed = 115200
upload_port = ${sysenv.ESP32_COM_PORT}
monitor_port = ${sysenv.ESP32_COM_PORT}
upload_protocol = esptool
monitor_filters = 
	esp32_exception_decoder
	log2file

[env:development_hub1]
; Common settings
extra_scripts = ${common.extra_scripts}
platform = ${common.platform}
platform_packages = ${common.platform_packages}
board = ${common.board}
framework = ${common.framework}

; Build options
build_unflags = ${common.build_unflags}
build_flags =
		${common.build_flags}
		-D LAYRZ_HUB1_BUILD
		-D LOCAL_COMPILATION
board_build.partitions = ${common.board_build.partitions}
board_build.sdkconfig = ${common.board_build.sdkconfig}

; Dependencies
lib_deps = ${common.lib_deps}

; Watchers
monitor_speed = ${common.monitor_speed}
upload_port = ${common.upload_port}
monitor_port = ${common.monitor_port}
upload_protocol = ${common.upload_protocol}
monitor_filters = ${common.monitor_filters}

[env:production_hub1]
; Common settings
extra_scripts = 
	${common.extra_scripts}
platform = ${common.platform}
platform_packages = ${common.platform_packages}
board = ${common.board}
framework = ${common.framework}

; Build options
build_unflags = ${common.build_unflags}
build_flags =
		${common.build_flags}
		-D LAYRZ_HUB1_BUILD
		-D BUILD_NUMBER=${sysenv.LAYRZ_BUILD_NUMBER}
board_build.partitions = ${common.board_build.partitions}
board_build.sdkconfig = ${common.board_build.sdkconfig}

; Dependencies
lib_deps = ${common.lib_deps}

; Watchers
monitor_speed = ${common.monitor_speed}
upload_port = ${common.upload_port}
monitor_port = ${common.monitor_port}
upload_protocol = ${common.upload_protocol}
monitor_filters = ${common.monitor_filters}

[env:development_hub2]
; Common settings
extra_scripts = ${common.extra_scripts}
platform = ${common.platform}
platform_packages = ${common.platform_packages}
board = ${common.board}
framework = ${common.framework}

; Build options
build_unflags = ${common.build_unflags}
build_flags =
		${common.build_flags}
		-D LOCAL_COMPILATION
		-D LAYRZ_HUB2_BUILD
		-D USE_ASYNC_A7670
board_build.partitions = ${common.board_build.partitions}
board_build.sdkconfig = ${common.board_build.sdkconfig}

; Dependencies
lib_deps = ${common.lib_deps}

; Watchers
monitor_speed = ${common.monitor_speed}
; upload_port = ${common.upload_port}
; monitor_port = ${common.monitor_port}
upload_protocol = ${common.upload_protocol}
monitor_filters = ${common.monitor_filters}

[env:production_hub2]
; Common settings
extra_scripts = 
	${common.extra_scripts}
platform = ${common.platform}
platform_packages = ${common.platform_packages}
board = ${common.board}
framework = ${common.framework}

; Build options
build_unflags = ${common.build_unflags}
build_flags =
		${common.build_flags}
		-D LAYRZ_HUB2_BUILD
		-D BUILD_NUMBER=${sysenv.LAYRZ_BUILD_NUMBER}
		; -D ARDUINO_USB_CDC_ON_BOOT=0
    ; -D CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG=0
    ; -D CONFIG_USB_DEVICE_ENABLED=0
board_build.partitions = ${common.board_build.partitions}
board_build.sdkconfig = ${common.board_build.sdkconfig}

; Dependencies
lib_deps = ${common.lib_deps}

; Watchers
monitor_speed = ${common.monitor_speed}
; upload_port = ${common.upload_port}
; monitor_port = ${common.monitor_port}
upload_protocol = ${common.upload_protocol}
monitor_filters = ${common.monitor_filters}


[env:development_hub25]
; Common settings
extra_scripts = ${common.extra_scripts}
platform = ${common.platform}
platform_packages = ${common.platform_packages}
board = ${common.board}
framework = ${common.framework}

; Build options
build_unflags = ${common.build_unflags}
build_flags =
		${common.build_flags}
		-D LOCAL_COMPILATION
		-D LAYRZ_HUB25_BUILD
		-D USE_ASYNC_A7670
board_build.partitions = ${common.board_build.partitions}
board_build.sdkconfig = ${common.board_build.sdkconfig}

; Dependencies
lib_deps = ${common.lib_deps}

; Watchers
monitor_speed = ${common.monitor_speed}
upload_port = ${common.upload_port}
monitor_port = ${common.monitor_port}
upload_protocol = ${common.upload_protocol}
monitor_filters = ${common.monitor_filters}

[env:production_hub25]
; Common settings
extra_scripts = 
	${common.extra_scripts}
platform = ${common.platform}
platform_packages = ${common.platform_packages}
board = ${common.board}
framework = ${common.framework}

; Build options
build_unflags = ${common.build_unflags}
build_flags =
		${common.build_flags}
		-D LAYRZ_HUB25_BUILD
		-D BUILD_NUMBER=${sysenv.LAYRZ_BUILD_NUMBER}
    ; -D CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG=0
    ; -D CONFIG_USB_DEVICE_ENABLED=0
board_build.partitions = ${common.board_build.partitions}
board_build.sdkconfig = ${common.board_build.sdkconfig}

; Dependencies
lib_deps = ${common.lib_deps}

; Watchers
monitor_speed = ${common.monitor_speed}
upload_port = ${common.upload_port}
monitor_port = ${common.monitor_port}
upload_protocol = ${common.upload_protocol}
monitor_filters = ${common.monitor_filters}
